
# This configuration doesn't handle border radius, glow
# or transparency, as the only responsability this program
# has is to provide a bar, use picom for border radius...

# The launcher position, top or bottom.
position = "top"

# The launcher separation from the screen borders [x, y].
padding = [0, 0]
height = 6

# The launcher background color.
background_color = 0x292929
# The launcher general text color.
text_color = 0xFFFFFF
# The launcher entry selection color.
selection_color = 0x666666
