## RMENU CONFIGURATION

# This configuration doesn't handle border radius, glow
# or transparency, as the only responsability this program
# has is to provide a launcher bar.

## POSITIONS

# The launcher position, top or bottom.
position = "top"

# The launcher separation from the screen borders.
#
# The type is a vector represented as a matrix
# or size 2 array [x, y].
padding = [0, 0]

# The launcher window height.
#
# The width is always 100% of the screen
# you can modify it using the `padding.x` value.
height = 20


## BAR COLORS

# All the bar colors have the same type, you
# may use an array of size 3 ([r, g, b]) or
# an hexadecimal value 0xRRGGBB.

# The launcher background color.
background_color = 0x292929

# The launcher general text color.
text_color = 0xFFFFFF

# The launcher entry selection color.
selection_color = 0x666666

# The launcher entry selection text color.
selection_text_color = 0xFFFFFF

## FONT CONFIGURATION

# The application font, a system path, `./` is the path
# from where you started the program.
#
# If starting the program from your window manager the path
# will be usually $HOME.
#
# The path must exist and be available, if this is not
# present a default font will be used instead.
#
# BASH EXPANSION IS NOT AVAILABLE IN THIS STRING.
# font_path = "./change_me.ttf"

# The font size.
#
# This will define the size of all fonts in the program,
# the autocomplete bar loads a dynamic number of entries
# depending on the size 'x' so they all fit on screen.
#
# If you set a font too big you might see 0 entries
# on the autocomplete menu or other undefined behavior.
#
# This gets clamped to u16::max and if decimal rounded
# towards 0.
font_size = 14


# If you would like to see more configuration, please
# open an issue or pull request at
#
# https://github.com/stifskere/rmenu
#
# Thanks for using r-menu.
